// The roster knowledge and identity the live assistant speaks from.
// roster-context.js is generated by `npm run build`. The local server swaps in a fresh copy after every rescan
// by setting globalThis.__JARVIS_CTX__, so a running server never needs a restart.
import * as generated from "./roster-context.js";

export function ctx() {
  return globalThis.__JARVIS_CTX__ || generated;
}
